addSbtPlugin("io.spray" % "sbt-revolver" % "0.9.0")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.5.1")
addSbtPlugin("au.com.onegeek" %% "sbt-dotenv" % "1.2.88")
addSbtPlugin("com.typesafe.sbt" % "sbt-git" % "0.9.3")
addSbtPlugin("com.julianpeeters" % "sbt-avrohugger" % "2.0.0-RC1")
